import type { LevelConfig } from '../../types/game';

export const LEVELS: LevelConfig[] = [
  {
    id: 'frutico',
    name: 'Frutico',
    displayName: 'Frutico 🍎',
    emoji: '🍎',
    colors: {
      primary: '#22C55E',
      secondary: '#16A34A',
      background: '#064E3B',
    },
    items: [
      { name: 'Apfel', emoji: '🍎', weight: 1.0 },
      { name: 'Birne', emoji: '🍐', weight: 1.0 },
      { name: 'Orange', emoji: '🍊', weight: 1.1 },
      { name: 'Traube', emoji: '🍇', weight: 0.8 },
      { name: 'Tomate', emoji: '🍅', weight: 0.9 },
      { name: 'Karotte', emoji: '🥕', weight: 1.0 },
      { name: 'Salat', emoji: '🥬', weight: 0.7 },
    ],
    baseSpeed: 120,
    spawnInterval: 1.2,
    spoiledChance: 0.12,
    goldenChance: 0,
  },
  {
    id: 'meatico',
    name: 'Meatico',
    displayName: 'Meatico 🥩',
    emoji: '🥩',
    colors: {
      primary: '#DC2626',
      secondary: '#991B1B',
      background: '#451A03',
    },
    items: [
      { name: 'Steak', emoji: '🥩', weight: 1.4 },
      { name: 'Poulet', emoji: '🍗', weight: 1.2 },
      { name: 'Würstchen', emoji: '🌭', weight: 1.0 },
      { name: 'Speck', emoji: '🥓', weight: 1.1 },
      { name: 'Hackfleisch', emoji: '🍖', weight: 1.3 },
    ],
    baseSpeed: 150,
    spawnInterval: 1.0,
    spoiledChance: 0.15,
    goldenChance: 0,
  },
  {
    id: 'lattico',
    name: 'Lattico',
    displayName: 'Lattico 🧀',
    emoji: '🧀',
    colors: {
      primary: '#EAB308',
      secondary: '#CA8A04',
      background: '#422006',
    },
    items: [
      { name: 'Käse', emoji: '🧀', weight: 1.0 },
      { name: 'Milch', emoji: '🥛', weight: 1.1 },
      { name: 'Butter', emoji: '🧈', weight: 0.9 },
      { name: 'Joghurt', emoji: '🫙', weight: 1.0 },
      { name: 'Eiscreme', emoji: '🍦', weight: 0.8 },
    ],
    baseSpeed: 170,
    spawnInterval: 0.9,
    spoiledChance: 0.15,
    goldenChance: 0.05,
  },
  {
    id: 'fontico',
    name: 'Fontico',
    displayName: 'Fontico 🥤',
    emoji: '🥤',
    colors: {
      primary: '#3B82F6',
      secondary: '#1D4ED8',
      background: '#0C1445',
    },
    items: [
      { name: 'Saft', emoji: '🧃', weight: 1.0 },
      { name: 'Smoothie', emoji: '🥤', weight: 1.1 },
      { name: 'Wasser', emoji: '💧', weight: 0.9 },
      { name: 'Limonade', emoji: '🍋', weight: 1.0 },
      { name: 'Tee', emoji: '🍵', weight: 0.8 },
    ],
    baseSpeed: 190,
    spawnInterval: 0.8,
    spoiledChance: 0.15,
    goldenChance: 0.05,
  },
  {
    id: 'crustico',
    name: 'Crustico',
    displayName: 'Crustico 🥐',
    emoji: '🥐',
    colors: {
      primary: '#D97706',
      secondary: '#B45309',
      background: '#451A03',
    },
    items: [
      { name: 'Croissant', emoji: '🥐', weight: 0.6 },
      { name: 'Brot', emoji: '🍞', weight: 1.3 },
      { name: 'Bretzel', emoji: '🥨', weight: 0.9 },
      { name: 'Kuchen', emoji: '🍰', weight: 1.0 },
      { name: 'Cookie', emoji: '🍪', weight: 0.8 },
      { name: 'Muffin', emoji: '🧁', weight: 0.9 },
    ],
    baseSpeed: 210,
    spawnInterval: 0.7,
    spoiledChance: 0.18,
    goldenChance: 0.07,
  },
];

export const ENDLESS_LEVEL: LevelConfig = {
  id: 'endless',
  name: 'Endlos',
  displayName: 'Endlos-Modus 🌟',
  emoji: '🌟',
  colors: {
    primary: '#8B5CF6',
    secondary: '#6D28D9',
    background: '#1E1B4B',
  },
  items: LEVELS.flatMap((l) => l.items),
  baseSpeed: 200,
  spawnInterval: 0.6,
  spoiledChance: 0.18,
  goldenChance: 0.08,
};
